region_names <- c('Винница', 'Волынь', 'Днепропетровск', 'Донецк', 'Житомир', 'Закарпатье', 'Запорожье', 'Ивано-Франковск', 'Киев', 'Киевская область', 'Кировоград', 'Крым', 'Луганск', 'Львов', 'Николаев', 'Одесса', 'Полтава', 'Ровно', 'Севастополь', 'Сумы', 'Тернополь', 'Харьков', 'Херсон', 'Хмельницкий', 'Черкасы', 'Чернигов', 'Черновцы')

regionName <- function(index){
  if (index == 1)
    return ("Черкасы")
  else if (index == 2)
    return ("Чернигов")
  else if (index == 3)
    return ("Черновцы")
  else if (index == 4)
    return ("Крым")
  else if (index == 5)
    return ("Днепропетровск")
  else if (index == 6)
    return ("Донецк")
  else if (index == 7)
    return ("Ивано-Франковск")
  else if (index == 8)
    return ("Харьков")
  else if (index == 9)
    return ("Херсон")
  else if (index == 10)
    return ("Хмельницкий")
  else if (index == 11)
    return ("Киев")
  else if (index == 12)
    return ("Киевская область")
  else if (index == 13)
    return ("Кировоград")
  else if (index == 14)
    return ("Луганск")
  else if (index == 15)
    return ("Львов")
  else if (index == 16)
    return ("Николаев")
  else if (index == 17)
    return ("Одесса")
  else if (index == 18)
    return ("Полтава")
  else if (index == 19)
    return ("Ровно")
  else if (index == 20)
    return ("Севастополь")
  else if (index == 21)
    return ("Сумы")
  else if (index == 22)
    return ("Тернополь")
  else if (index == 23)
    return ("Закарпатье")
  else if (index == 24)
    return ("Винница")
  else if (index == 25)
    return ("Волынь")
  else if (index == 26)
    return ("Запорожье")
  else if (index == 27)
    return ("Житомир")
}
plotMake <- function(region, data){
  reg.path <- paste0("data/clean/", list.files(path = "data/clean/", pattern = glob2rx(paste0("?? ", region, " ????-??-?? ??:??:??.csv"))))
  table <- read.csv(reg.path)
  plot(with(table, get(data)), type = "l", col = "blue", ann = F, xaxt = "n",  xlab = "")
  title(main=region, font.main=4)
  title(xlab="Недели")
  title(ylab=data)
  return (table)
}
extCount <- function(df, data = "VHI", year.from = 1981, year.to = 9999) {
  df <- subset(df , Год >= year.from & Год <= year.to)
  df.max <- max(df[data])
  df.min <- min(df[data])
  cat("Максимальное значение ", data, ": ", df.max, "\n")
  cat("Минимальное значение ", data, ": ", df.min)
}
area <- function(df, percent, VHI.35) {
  if (VHI.35 == F){
    df <- df[df$Процент.площади.где.VHI...15. > percent,]
    df <- subset(df, select=c("Год", "Неделя", "Процент.площади.где.VHI...15."))
  }
  else{
    df <- df[df$Процент.площади.где.VHI...35. > percent,]
    df <- subset(df, select=c("Год", "Неделя", "Процент.площади.где.VHI...35."))
  }
  print(df)
}